# fly.toml app configuration file generated for expensetrackermm on 2023-07-21T20:50:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "expensetrackermm"
primary_region = "otp"

[build]
  image = "marceticm/expensetracker:latest"
  
[env]
	ASPNETCORE_URLS="http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
